# Generated by Django 3.1.2 on 2020-12-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201215_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='category',
            field=models.CharField(choices=[('sports', 'sports'), ('entertainment', 'entertainment'), ('Business', 'Business'), ('Politics', 'Politics'), ('All', 'read')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
